# Generated by Django 4.1 on 2024-06-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBanner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bannername', models.CharField(blank=True, max_length=200, verbose_name='Banner Name')),
                ('about_banner', models.ImageField(blank=True, upload_to='img/', verbose_name='Banner Size 1440*961')),
            ],
        ),
        migrations.CreateModel(
            name='AboutPageFirstContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contentname', models.CharField(blank=True, max_length=1000, verbose_name='ContentName')),
                ('heading', models.CharField(blank=True, max_length=1000, verbose_name='Heading')),
                ('paragraph', models.CharField(blank=True, max_length=1000, verbose_name='Paragraph')),
                ('first_small_heading', models.CharField(blank=True, max_length=1000, verbose_name='First Small Heading')),
                ('first_paragraph', models.CharField(blank=True, max_length=1000, verbose_name='First Paragraph')),
                ('second_small_heading', models.CharField(blank=True, max_length=1000, verbose_name='Second Small Heading')),
                ('second_paragraph', models.CharField(blank=True, max_length=1000, verbose_name='Second Paragraph')),
                ('third_small_heading', models.CharField(blank=True, max_length=1000, verbose_name='Third Small Heading')),
                ('third_paragraph', models.CharField(blank=True, max_length=1000, verbose_name='Third Paragraph')),
            ],
        ),
        migrations.CreateModel(
            name='AboutPageFourthContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contentname', models.CharField(blank=True, max_length=1000, verbose_name='ContentName')),
                ('heading', models.CharField(blank=True, max_length=1000, verbose_name='Heading')),
                ('paragraph', models.CharField(blank=True, max_length=1000, verbose_name='Paragraph')),
                ('img_1', models.ImageField(blank=True, upload_to='img/', verbose_name='First image Size 408*531')),
                ('img_2', models.ImageField(blank=True, upload_to='img/', verbose_name='Second image Size 408*531')),
                ('img_3', models.ImageField(blank=True, upload_to='img/', verbose_name='Third image Size 408*531')),
                ('img_4', models.ImageField(blank=True, upload_to='img/', verbose_name='Fourth image Size 730*250')),
                ('img_5', models.ImageField(blank=True, upload_to='img/', verbose_name='Fifth image Size 730*250')),
                ('link_1', models.CharField(blank=True, max_length=200, verbose_name='link_1')),
                ('link_2', models.CharField(blank=True, max_length=200, verbose_name='link_2')),
                ('link_3', models.CharField(blank=True, max_length=200, verbose_name='link_3')),
                ('link_4', models.CharField(blank=True, max_length=200, verbose_name='link_4')),
                ('link_5', models.CharField(blank=True, max_length=200, verbose_name='link_5')),
            ],
        ),
        migrations.CreateModel(
            name='AboutPageSecondContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contentname', models.CharField(blank=True, max_length=1000, verbose_name='ContentName')),
                ('heading', models.CharField(blank=True, max_length=1000, verbose_name='Heading')),
                ('paragraph', models.CharField(blank=True, max_length=1000, verbose_name='Paragraph')),
                ('first_small_heading', models.CharField(blank=True, max_length=1000, verbose_name='First Small Heading')),
                ('first_paragraph', models.CharField(blank=True, max_length=1000, verbose_name='First Paragraph')),
                ('second_small_heading', models.CharField(blank=True, max_length=1000, verbose_name='Second Small Heading')),
                ('second_paragraph', models.CharField(blank=True, max_length=1000, verbose_name='Second Paragraph')),
                ('third_small_heading', models.CharField(blank=True, max_length=1000, verbose_name='Third Small Heading')),
                ('third_paragraph', models.CharField(blank=True, max_length=1000, verbose_name='Third Paragraph')),
                ('left_img', models.ImageField(blank=True, upload_to='img/', verbose_name='Left image Size 996*696')),
                ('img_heading', models.CharField(blank=True, max_length=1000, verbose_name='Img Heading')),
                ('img_paragraph', models.CharField(blank=True, max_length=1000, verbose_name='Img Paragraph')),
            ],
        ),
        migrations.CreateModel(
            name='AboutPageThirdContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contentname', models.CharField(blank=True, max_length=1000, verbose_name='ContentName')),
                ('first_small_heading', models.CharField(blank=True, max_length=1000, verbose_name='First Small Heading')),
                ('first_paragraph', models.CharField(blank=True, max_length=1000, verbose_name='First Paragraph')),
                ('second_small_heading', models.CharField(blank=True, max_length=1000, verbose_name='Second Small Heading')),
                ('second_paragraph', models.CharField(blank=True, max_length=1000, verbose_name='Second Paragraph')),
                ('third_small_heading', models.CharField(blank=True, max_length=1000, verbose_name='Third Small Heading')),
                ('third_paragraph', models.CharField(blank=True, max_length=1000, verbose_name='Third Paragraph')),
                ('right_img', models.ImageField(blank=True, upload_to='img/', verbose_name='Right image Size 1000*750')),
                ('img_heading', models.CharField(blank=True, max_length=1000, verbose_name='Img Heading')),
                ('img_paragraph', models.CharField(blank=True, max_length=1000, verbose_name='Img Paragraph')),
            ],
        ),
        migrations.CreateModel(
            name='catalouge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cat', models.CharField(blank=True, max_length=200, verbose_name='Name')),
                ('cat_pdf', models.FileField(null=True, upload_to='catalouge/')),
            ],
        ),
        migrations.CreateModel(
            name='ContactBanner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bannername', models.CharField(blank=True, max_length=200, verbose_name='Banner Name')),
                ('contact_banner', models.ImageField(blank=True, upload_to='img/', verbose_name='Banner image Size 1440*960')),
            ],
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Office Address')),
                ('marketing_phone', models.CharField(blank=True, max_length=200, verbose_name='Marketing Person Phone Number')),
                ('marketing_email', models.CharField(blank=True, max_length=200, verbose_name='Marketing Person Email')),
                ('production_phone', models.CharField(blank=True, max_length=200, verbose_name='Production Person Phone Number')),
                ('production_email', models.CharField(blank=True, max_length=200, verbose_name='Production Person Phone Number')),
            ],
        ),
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Name')),
                ('email', models.CharField(blank=True, max_length=200, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=17, verbose_name='phone')),
                ('message', models.TextField(blank=True, max_length=200, verbose_name='Message')),
            ],
        ),
        migrations.CreateModel(
            name='ebooks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Ebook Name')),
                ('ebook', models.CharField(blank=True, max_length=200, verbose_name='Ebook Url')),
            ],
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bannername', models.CharField(blank=True, max_length=200, verbose_name='Banner Name')),
                ('first_banner', models.ImageField(blank=True, upload_to='img/', verbose_name='First Banner 4928*3264')),
                ('first_banner_heading', models.CharField(blank=True, max_length=200, verbose_name='First Banner Heading')),
                ('first_banner_paragraph', models.CharField(blank=True, max_length=200, verbose_name='First Banner Paragraph')),
                ('second_banner', models.ImageField(blank=True, upload_to='img/', verbose_name='Second Banner 4928*3264')),
                ('second_banner_heading', models.CharField(blank=True, max_length=200, verbose_name='Second Banner Heading')),
                ('second_banner_paragraph', models.CharField(blank=True, max_length=200, verbose_name='Second Banner Paragraph')),
                ('third_banner', models.ImageField(blank=True, upload_to='img/', verbose_name='Third Banner 4928*3264')),
                ('third_banner_heading', models.CharField(blank=True, max_length=200, verbose_name='Third Banner Heading')),
                ('third_banner_paragraph', models.CharField(blank=True, max_length=200, verbose_name='Third Banner Paragraph')),
            ],
        ),
        migrations.CreateModel(
            name='HomePageFirstContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contentname', models.CharField(blank=True, max_length=1000, verbose_name='ContentName')),
                ('heading', models.CharField(blank=True, max_length=1000, verbose_name='Heading')),
                ('paragraph', models.CharField(blank=True, max_length=1000, verbose_name='Paragraph')),
                ('first_img', models.ImageField(blank=True, upload_to='img/', verbose_name='First Image Size 3861*2574')),
                ('second_img', models.ImageField(blank=True, upload_to='img/', verbose_name='Second Image Size 3861*2574')),
                ('second_heading', models.CharField(blank=True, max_length=1000, verbose_name='Second Heading')),
                ('second_paragraph', models.CharField(blank=True, max_length=1000, verbose_name='Second Paragraph')),
                ('third_paragraph', models.CharField(blank=True, max_length=1000, verbose_name='Third Paragraph')),
                ('fourth_paragraph', models.CharField(blank=True, max_length=1000, verbose_name='Fourth Paragraph')),
                ('left_img', models.ImageField(blank=True, upload_to='img/', verbose_name='Left Image Size 3861*2574')),
            ],
        ),
        migrations.CreateModel(
            name='HomePageSecondContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contentname', models.CharField(blank=True, max_length=1000, verbose_name='ContentName')),
                ('heading', models.CharField(blank=True, max_length=1000, verbose_name='Heading')),
                ('small_heading', models.CharField(blank=True, max_length=1000, verbose_name='Small Heading')),
                ('paragraph', models.CharField(blank=True, max_length=1000, verbose_name='Paragraph')),
                ('left_img', models.ImageField(blank=True, upload_to='img/', verbose_name='First Image Size 408*531')),
                ('point_1', models.CharField(blank=True, max_length=1000, verbose_name='Point 1')),
                ('point_2', models.CharField(blank=True, max_length=1000, verbose_name='Point 2')),
                ('point_3', models.CharField(blank=True, max_length=1000, verbose_name='Point 3')),
                ('point_4', models.CharField(blank=True, max_length=1000, verbose_name='Point 4')),
                ('point_5', models.CharField(blank=True, max_length=1000, verbose_name='Point 5')),
                ('point_6', models.CharField(blank=True, max_length=1000, verbose_name='Point 6')),
                ('point_7', models.CharField(blank=True, max_length=1000, verbose_name='Point 7')),
                ('second_small_heading', models.CharField(blank=True, max_length=1000, verbose_name='Small Heading')),
                ('second_paragraph', models.CharField(blank=True, max_length=1000, verbose_name='Paragraph')),
                ('right_img', models.ImageField(blank=True, upload_to='img/', verbose_name='Second Image Size 408*531')),
                ('second_point_1', models.CharField(blank=True, max_length=1000, verbose_name='Point 1')),
                ('second_point_2', models.CharField(blank=True, max_length=1000, verbose_name='Point 2')),
                ('second_point_3', models.CharField(blank=True, max_length=1000, verbose_name='Point 3')),
                ('second_point_4', models.CharField(blank=True, max_length=1000, verbose_name='Point 4')),
                ('second_point_5', models.CharField(blank=True, max_length=1000, verbose_name='Point 5')),
                ('second_point_6', models.CharField(blank=True, max_length=1000, verbose_name='Point 6')),
                ('second_point_7', models.CharField(blank=True, max_length=1000, verbose_name='Point 7')),
                ('second_point_8', models.CharField(blank=True, max_length=1000, verbose_name='Point 8')),
                ('second_point_9', models.CharField(blank=True, max_length=1000, verbose_name='Point 9')),
                ('second_point_10', models.CharField(blank=True, max_length=1000, verbose_name='Point 10')),
            ],
        ),
        migrations.CreateModel(
            name='socialmedia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('social', models.CharField(blank=True, max_length=200, verbose_name='Social Media')),
                ('facebook', models.CharField(blank=True, max_length=200, verbose_name='Facebook')),
                ('instagram', models.CharField(blank=True, max_length=200, verbose_name='Instagram')),
                ('youtube', models.CharField(blank=True, max_length=200, verbose_name='Youtube')),
                ('twitter', models.CharField(blank=True, max_length=200, verbose_name='Twitter')),
            ],
        ),
    ]
