# Generated by Django 3.0.7 on 2021-02-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Name')),
                ('email', models.CharField(blank=True, max_length=200, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=17, verbose_name='phone')),
                ('message', models.TextField(blank=True, max_length=200, verbose_name='Message')),
            ],
        ),
    ]
