# Generated by Django 4.0.6 on 2025-04-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='bannername',
            field=models.CharField(max_length=200, verbose_name='Banner Name'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='first_banner',
            field=models.ImageField(upload_to='img/', verbose_name='First Banner 4928*3264'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='first_banner_heading',
            field=models.CharField(max_length=200, verbose_name='First Banner Heading'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='first_banner_paragraph',
            field=models.CharField(max_length=200, verbose_name='First Banner Paragraph'),
        ),
    ]
