# Generated by Django 3.0.7 on 2021-03-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='workwithus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Name')),
                ('email', models.CharField(blank=True, max_length=200, verbose_name='Email')),
                ('speciality', models.TextField(blank=True, max_length=200, verbose_name='Message')),
            ],
        ),
    ]
