# Generated by Django 3.0.7 on 2021-09-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_workwithus'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bannername', models.CharField(blank=True, max_length=200, verbose_name='Banner Name')),
                ('first_banner', models.ImageField(blank=True, upload_to='img')),
                ('first_banner_heading', models.CharField(blank=True, max_length=200, verbose_name='Banner Heading')),
                ('first_banner_paragraph', models.CharField(blank=True, max_length=200, verbose_name='Banner Paragraph')),
                ('second_banner', models.ImageField(blank=True, upload_to='img')),
                ('second_banner_heading', models.CharField(blank=True, max_length=200, verbose_name='Banner Heading')),
                ('second_banner_paragraph', models.CharField(blank=True, max_length=200, verbose_name='Banner Paragraph')),
                ('third_banner', models.ImageField(blank=True, upload_to='img')),
                ('third_banner_heading', models.CharField(blank=True, max_length=200, verbose_name='Banner Heading')),
                ('third_banner_paragraph', models.CharField(blank=True, max_length=200, verbose_name='Banner Paragraph')),
            ],
        ),
        migrations.DeleteModel(
            name='workwithus',
        ),
    ]
