# Generated by Django 3.0.7 on 2021-09-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210930_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='first_banner',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='second_banner',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='third_banner',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
    ]
