# Generated by Django 3.0.7 on 2021-09-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210930_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
