# Generated by Django 3.0.7 on 2021-09-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210930_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBanner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bannername', models.CharField(blank=True, max_length=200, verbose_name='Banner Name')),
                ('about_banner', models.ImageField(blank=True, upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='ContactBanner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bannername', models.CharField(blank=True, max_length=200, verbose_name='Banner Name')),
                ('contact_banner', models.ImageField(blank=True, upload_to='img/')),
            ],
        ),
    ]
