# Generated by Django 3.0.7 on 2021-09-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_aboutbanner_contactbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageFirstContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contentname', models.CharField(blank=True, max_length=200, verbose_name='Banner Name')),
                ('heading', models.CharField(blank=True, max_length=200, verbose_name='Heading')),
                ('paragraph', models.CharField(blank=True, max_length=200, verbose_name='Paragraph')),
                ('first_img', models.ImageField(blank=True, upload_to='img/')),
                ('second_img', models.ImageField(blank=True, upload_to='img/')),
                ('second_heading', models.CharField(blank=True, max_length=200, verbose_name='Banner Heading')),
                ('second_paragraph', models.CharField(blank=True, max_length=200, verbose_name='Banner Paragraph')),
                ('third_paragraph', models.CharField(blank=True, max_length=200, verbose_name='Banner Paragraph')),
                ('fourth_paragraph', models.CharField(blank=True, max_length=200, verbose_name='Banner Paragraph')),
                ('left_img', models.ImageField(blank=True, upload_to='img/')),
            ],
        ),
    ]
