# Generated by Django 3.0.7 on 2021-09-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepagefirstcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagefirstcontent',
            name='contentname',
            field=models.CharField(blank=True, max_length=1000, verbose_name='ContentName'),
        ),
        migrations.AlterField(
            model_name='homepagefirstcontent',
            name='fourth_paragraph',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Fourth Paragraph'),
        ),
        migrations.AlterField(
            model_name='homepagefirstcontent',
            name='heading',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='homepagefirstcontent',
            name='paragraph',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Paragraph'),
        ),
        migrations.AlterField(
            model_name='homepagefirstcontent',
            name='second_heading',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Second Heading'),
        ),
        migrations.AlterField(
            model_name='homepagefirstcontent',
            name='second_paragraph',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Second Paragraph'),
        ),
        migrations.AlterField(
            model_name='homepagefirstcontent',
            name='third_paragraph',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Third Paragraph'),
        ),
    ]
