# Generated by Django 3.0.7 on 2021-09-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210930_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSecondContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contentname', models.CharField(blank=True, max_length=1000, verbose_name='ContentName')),
                ('heading', models.CharField(blank=True, max_length=1000, verbose_name='Heading')),
                ('small_heading', models.CharField(blank=True, max_length=1000, verbose_name='Small Heading')),
                ('paragraph', models.CharField(blank=True, max_length=1000, verbose_name='Paragraph')),
                ('left_img', models.ImageField(blank=True, upload_to='img/')),
                ('point_1', models.CharField(blank=True, max_length=1000, verbose_name='Point 1')),
                ('point_2', models.CharField(blank=True, max_length=1000, verbose_name='Point 2')),
                ('point_3', models.CharField(blank=True, max_length=1000, verbose_name='Point 3')),
                ('point_4', models.CharField(blank=True, max_length=1000, verbose_name='Point 4')),
                ('point_5', models.CharField(blank=True, max_length=1000, verbose_name='Point 5')),
                ('point_6', models.CharField(blank=True, max_length=1000, verbose_name='Point 6')),
                ('point_7', models.CharField(blank=True, max_length=1000, verbose_name='Point 7')),
                ('point_8', models.CharField(blank=True, max_length=1000, verbose_name='Point 8')),
                ('point_9', models.CharField(blank=True, max_length=1000, verbose_name='Point 9')),
                ('point_10', models.CharField(blank=True, max_length=1000, verbose_name='Point 10')),
                ('second_small_heading', models.CharField(blank=True, max_length=1000, verbose_name='Small Heading')),
                ('second_paragraph', models.CharField(blank=True, max_length=1000, verbose_name='Paragraph')),
                ('right_img', models.ImageField(blank=True, upload_to='img/')),
                ('second_point_1', models.CharField(blank=True, max_length=1000, verbose_name='Point 1')),
                ('second_point_2', models.CharField(blank=True, max_length=1000, verbose_name='Point 2')),
                ('second_point_3', models.CharField(blank=True, max_length=1000, verbose_name='Point 3')),
                ('second_point_4', models.CharField(blank=True, max_length=1000, verbose_name='Point 4')),
                ('second_point_5', models.CharField(blank=True, max_length=1000, verbose_name='Point 5')),
                ('second_point_6', models.CharField(blank=True, max_length=1000, verbose_name='Point 6')),
                ('second_point_7', models.CharField(blank=True, max_length=1000, verbose_name='Point 7')),
                ('second_point_8', models.CharField(blank=True, max_length=1000, verbose_name='Point 8')),
                ('second_point_9', models.CharField(blank=True, max_length=1000, verbose_name='Point 9')),
                ('second_point_10', models.CharField(blank=True, max_length=1000, verbose_name='Point 10')),
            ],
        ),
    ]
