# Generated by Django 3.0.7 on 2021-09-30 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homepagesecondcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagesecondcontent',
            name='point_10',
        ),
        migrations.RemoveField(
            model_name='homepagesecondcontent',
            name='point_8',
        ),
        migrations.RemoveField(
            model_name='homepagesecondcontent',
            name='point_9',
        ),
    ]
