# Generated by Django 3.0.7 on 2021-09-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210930_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageFirstContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contentname', models.CharField(blank=True, max_length=1000, verbose_name='ContentName')),
                ('heading', models.CharField(blank=True, max_length=1000, verbose_name='Heading')),
                ('paragraph', models.CharField(blank=True, max_length=1000, verbose_name='Paragraph')),
                ('first_small_heading', models.CharField(blank=True, max_length=1000, verbose_name='First Small Heading')),
                ('first_paragraph', models.CharField(blank=True, max_length=1000, verbose_name='First Paragraph')),
                ('second_small_heading', models.CharField(blank=True, max_length=1000, verbose_name='Second Small Heading')),
                ('second_paragraph', models.CharField(blank=True, max_length=1000, verbose_name='Second Paragraph')),
                ('third_small_heading', models.CharField(blank=True, max_length=1000, verbose_name='Third Small Heading')),
                ('third_paragraph', models.CharField(blank=True, max_length=1000, verbose_name='Third Paragraph')),
            ],
        ),
    ]
