# Generated by Django 3.0.7 on 2021-09-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_aboutpagesecondcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageThirdContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contentname', models.CharField(blank=True, max_length=1000, verbose_name='ContentName')),
                ('first_small_heading', models.CharField(blank=True, max_length=1000, verbose_name='First Small Heading')),
                ('first_paragraph', models.CharField(blank=True, max_length=1000, verbose_name='First Paragraph')),
                ('second_small_heading', models.CharField(blank=True, max_length=1000, verbose_name='Second Small Heading')),
                ('second_paragraph', models.CharField(blank=True, max_length=1000, verbose_name='Second Paragraph')),
                ('third_small_heading', models.CharField(blank=True, max_length=1000, verbose_name='Third Small Heading')),
                ('third_paragraph', models.CharField(blank=True, max_length=1000, verbose_name='Third Paragraph')),
                ('right_img', models.ImageField(blank=True, upload_to='img/')),
                ('img_heading', models.CharField(blank=True, max_length=1000, verbose_name='Img Heading')),
                ('img_paragraph', models.CharField(blank=True, max_length=1000, verbose_name='Img Paragraph')),
            ],
        ),
        migrations.RenameField(
            model_name='aboutpagesecondcontent',
            old_name='right_img',
            new_name='left_img',
        ),
    ]
