# Generated by Django 3.0.7 on 2021-09-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210930_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageFourthContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contentname', models.CharField(blank=True, max_length=1000, verbose_name='ContentName')),
                ('heading', models.CharField(blank=True, max_length=1000, verbose_name='Heading')),
                ('paragraph', models.CharField(blank=True, max_length=1000, verbose_name='Paragraph')),
                ('img_1', models.ImageField(blank=True, upload_to='img/')),
                ('img_2', models.ImageField(blank=True, upload_to='img/')),
                ('img_3', models.ImageField(blank=True, upload_to='img/')),
                ('img_4', models.ImageField(blank=True, upload_to='img/')),
                ('img_5', models.ImageField(blank=True, upload_to='img/')),
            ],
        ),
    ]
