# Generated by Django 3.0.7 on 2021-12-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_aboutpagefourthcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='first_banner',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='First Banner 4928*3264'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='second_banner',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='Second Banner 4928*3264'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='third_banner',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='Third Banner 4928*3264'),
        ),
    ]
