# Generated by Django 3.0.7 on 2021-12-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20211203_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='first_banner_heading',
            field=models.CharField(blank=True, max_length=200, verbose_name='First Banner Heading'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='first_banner_paragraph',
            field=models.CharField(blank=True, max_length=200, verbose_name='First Banner Paragraph'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='second_banner_heading',
            field=models.CharField(blank=True, max_length=200, verbose_name='Second Banner Heading'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='second_banner_paragraph',
            field=models.CharField(blank=True, max_length=200, verbose_name='Second Banner Paragraph'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='third_banner_heading',
            field=models.CharField(blank=True, max_length=200, verbose_name='Third Banner Heading'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='third_banner_paragraph',
            field=models.CharField(blank=True, max_length=200, verbose_name='Third Banner Paragraph'),
        ),
    ]
