# Generated by Django 3.0.7 on 2021-12-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20211203_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagefirstcontent',
            name='first_img',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='First Image Size 3861*2574'),
        ),
        migrations.AlterField(
            model_name='homepagefirstcontent',
            name='left_img',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='Left Image Size 3861*2574'),
        ),
        migrations.AlterField(
            model_name='homepagefirstcontent',
            name='second_img',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='Second Image Size 3861*2574'),
        ),
    ]
