# Generated by Django 3.0.7 on 2021-12-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20211203_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesecondcontent',
            name='left_img',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='First Image Size 408*531'),
        ),
        migrations.AlterField(
            model_name='homepagesecondcontent',
            name='right_img',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='Second Image Size 408*531'),
        ),
    ]
