# Generated by Django 3.0.7 on 2021-12-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20211203_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutbanner',
            name='about_banner',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='Banner Size 1440*961'),
        ),
    ]
