# Generated by Django 3.0.7 on 2021-12-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20211203_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpagethirdcontent',
            name='right_img',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='Right image Size 1000*750'),
        ),
    ]
