# Generated by Django 3.0.7 on 2021-12-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20211203_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpagefourthcontent',
            name='img_1',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='First image Size 408*531'),
        ),
        migrations.AlterField(
            model_name='aboutpagefourthcontent',
            name='img_2',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='Second image Size 408*531'),
        ),
        migrations.AlterField(
            model_name='aboutpagefourthcontent',
            name='img_3',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='Third image Size 408*531'),
        ),
        migrations.AlterField(
            model_name='aboutpagefourthcontent',
            name='img_4',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='Fourth image Size 730*250'),
        ),
        migrations.AlterField(
            model_name='aboutpagefourthcontent',
            name='img_5',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='Fifth image Size 730*250'),
        ),
    ]
