# Generated by Django 3.0.7 on 2021-12-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20211203_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactbanner',
            name='contact_banner',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='Banner image Size 1440*960'),
        ),
    ]
