# Generated by Django 3.0.7 on 2021-12-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20211203_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bannername', models.CharField(blank=True, max_length=200, verbose_name='Banner Name')),
                ('contact_banner', models.ImageField(blank=True, upload_to='img/', verbose_name='Banner image Size 1440*960')),
            ],
        ),
        migrations.RemoveField(
            model_name='contactbanner',
            name='bannername',
        ),
        migrations.RemoveField(
            model_name='contactbanner',
            name='contact_banner',
        ),
        migrations.AddField(
            model_name='contactbanner',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Office Address'),
        ),
        migrations.AddField(
            model_name='contactbanner',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='contactbanner',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='contactbanner',
            name='marketing_email',
            field=models.CharField(blank=True, max_length=200, verbose_name='Marketing Person Email'),
        ),
        migrations.AddField(
            model_name='contactbanner',
            name='marketing_phone',
            field=models.CharField(blank=True, max_length=200, verbose_name='Marketing Person Phone Number'),
        ),
        migrations.AddField(
            model_name='contactbanner',
            name='office_phone',
            field=models.CharField(blank=True, max_length=200, verbose_name='Office Phone Number'),
        ),
        migrations.AddField(
            model_name='contactbanner',
            name='production_email',
            field=models.CharField(blank=True, max_length=200, verbose_name='Production Person Phone Number'),
        ),
        migrations.AddField(
            model_name='contactbanner',
            name='production_phone',
            field=models.CharField(blank=True, max_length=200, verbose_name='Production Person Phone Number'),
        ),
        migrations.AddField(
            model_name='contactbanner',
            name='twitter_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='contactbanner',
            name='youtube_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='Youtube'),
        ),
    ]
