# Generated by Django 3.0.7 on 2021-12-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20211203_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactbanner',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contactbanner',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='contactbanner',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='contactbanner',
            name='marketing_email',
        ),
        migrations.RemoveField(
            model_name='contactbanner',
            name='marketing_phone',
        ),
        migrations.RemoveField(
            model_name='contactbanner',
            name='office_phone',
        ),
        migrations.RemoveField(
            model_name='contactbanner',
            name='production_email',
        ),
        migrations.RemoveField(
            model_name='contactbanner',
            name='production_phone',
        ),
        migrations.RemoveField(
            model_name='contactbanner',
            name='twitter_url',
        ),
        migrations.RemoveField(
            model_name='contactbanner',
            name='youtube_url',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='bannername',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='contact_banner',
        ),
        migrations.AddField(
            model_name='contactbanner',
            name='bannername',
            field=models.CharField(blank=True, max_length=200, verbose_name='Banner Name'),
        ),
        migrations.AddField(
            model_name='contactbanner',
            name='contact_banner',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='Banner image Size 1440*960'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Office Address'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='marketing_email',
            field=models.CharField(blank=True, max_length=200, verbose_name='Marketing Person Email'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='marketing_phone',
            field=models.CharField(blank=True, max_length=200, verbose_name='Marketing Person Phone Number'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='office_phone',
            field=models.CharField(blank=True, max_length=200, verbose_name='Office Phone Number'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='production_email',
            field=models.CharField(blank=True, max_length=200, verbose_name='Production Person Phone Number'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='production_phone',
            field=models.CharField(blank=True, max_length=200, verbose_name='Production Person Phone Number'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='twitter_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='youtube_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='Youtube'),
        ),
    ]
