# Generated by Django 3.0.7 on 2021-12-03 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20211203_1220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactPage',
        ),
    ]
