# Generated by Django 3.0.7 on 2021-12-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_delete_contactpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Office Address')),
                ('marketing_phone', models.CharField(blank=True, max_length=200, verbose_name='Marketing Person Phone Number')),
                ('marketing_email', models.CharField(blank=True, max_length=200, verbose_name='Marketing Person Email')),
                ('production_phone', models.CharField(blank=True, max_length=200, verbose_name='Production Person Phone Number')),
                ('production_email', models.CharField(blank=True, max_length=200, verbose_name='Production Person Phone Number')),
                ('office_phone', models.CharField(blank=True, max_length=200, verbose_name='Office Phone Number')),
                ('facebook_url', models.CharField(blank=True, max_length=200, verbose_name='Facebook')),
                ('instagram_url', models.CharField(blank=True, max_length=200, verbose_name='Instagram')),
                ('youtube_url', models.CharField(blank=True, max_length=200, verbose_name='Youtube')),
                ('twitter_url', models.CharField(blank=True, max_length=200, verbose_name='Twitter')),
            ],
        ),
    ]
