# Generated by Django 3.0.7 on 2021-12-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_contactpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='socialmedia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('social', models.CharField(blank=True, max_length=200, verbose_name='Social Media')),
                ('facebook_url', models.CharField(blank=True, max_length=200, verbose_name='Facebook')),
                ('instagram_url', models.CharField(blank=True, max_length=200, verbose_name='Instagram')),
                ('youtube_url', models.CharField(blank=True, max_length=200, verbose_name='Youtube')),
                ('twitter_url', models.CharField(blank=True, max_length=200, verbose_name='Twitter')),
            ],
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='office_phone',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='twitter_url',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='youtube_url',
        ),
    ]
