# Generated by Django 3.0.7 on 2021-12-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20211203_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='catalouge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cat', models.CharField(blank=True, max_length=200, verbose_name='Name')),
                ('cat_pdf', models.FileField(null=True, upload_to='catalouge/')),
            ],
        ),
    ]
