# Generated by Django 3.0.7 on 2021-12-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_catalouge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='social',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='twitter_url',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='ebook',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ebook Url'),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ebook Name'),
        ),
    ]
