# Generated by Django 3.0.7 on 2021-12-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20211203_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='ebooks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Ebook Name')),
                ('ebook', models.CharField(blank=True, max_length=200, verbose_name='Ebook Url')),
            ],
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='ebook',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='name',
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='social',
            field=models.CharField(blank=True, max_length=200, verbose_name='Social Media'),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='twitter',
            field=models.CharField(blank=True, max_length=200, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='youtube',
            field=models.CharField(blank=True, max_length=200, verbose_name='Youtube'),
        ),
    ]
