# Generated by Django 3.2.8 on 2022-01-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20211203_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagefourthcontent',
            name='link_1',
            field=models.CharField(blank=True, max_length=200, verbose_name='link_1'),
        ),
        migrations.AddField(
            model_name='aboutpagefourthcontent',
            name='link_2',
            field=models.CharField(blank=True, max_length=200, verbose_name='link_2'),
        ),
        migrations.AddField(
            model_name='aboutpagefourthcontent',
            name='link_3',
            field=models.CharField(blank=True, max_length=200, verbose_name='link_3'),
        ),
        migrations.AddField(
            model_name='aboutpagefourthcontent',
            name='link_4',
            field=models.CharField(blank=True, max_length=200, verbose_name='link_4'),
        ),
        migrations.AddField(
            model_name='aboutpagefourthcontent',
            name='link_5',
            field=models.CharField(blank=True, max_length=200, verbose_name='link_5'),
        ),
    ]
